### ISSUE TITLE
When stopping, an IllegalStateException is thrown

### ISSUE THREAD

**Issue by PattexPattex** [PattexPattex/ServerGods-2.0.0#6]
Example log:

```20:22:28.822 [ForkJoinPool.commonPool-worker-16] [n.d.jda.api.requests.RestAction] [ERROR] - Encountered error while processing success consumer
java.lang.IllegalStateException: Preventing use of complete() in callback threads! This operation can be a deadlock cause
        at net.dv8tion.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:216)
        at net.dv8tion.jda.api.requests.RestAction.complete(RestAction.java:633)
        at com.pattexpattex.servergods2.core.Kvintakord.updateLastQueueMessage(Kvintakord.java:814)
        at com.pattexpattex.servergods2.core.Kvintakord.stop(Kvintakord.java:590)
        ...
```

This will be fixed in the next commit.

**Comment by PattexPattex** [comment]
Fixed in db7496e0582778591e30ea80de214bac53914c59.
