### ISSUE TITLE
Add /music queue short to display a shorter variant of /music queue

### ISSUE THREAD

**Issue by PattexPattex** [PattexPattex/ServerGods-2.0.0#9]
When a long playlist/queue is present, updating the `/music queue` message throws an `IllegalArgumentException`, because the description is longer than 4096 chars.

- Will be worked on in the branch `kvintakord-rewrite`

- [x] - Prevent the exception being thrown
- [ ] - Add `/music queue short`

```
10:13:37.008 [JDA MainWS-ReadThread] [c.p.s.c.l.ButtonEventListener] [ERROR] - Something broke
java.lang.IllegalArgumentException: Description cannot be longer than 4096 characters.
        at net.dv8tion.jda.internal.utils.Checks.check(Checks.java:62)
        at net.dv8tion.jda.api.EmbedBuilder.appendDescription(EmbedBuilder.java:363)
        at net.dv8tion.jda.api.EmbedBuilder.setDescription(EmbedBuilder.java:338)
        at com.pattexpattex.servergods2.util.FormatUtil.defaultEmbed(FormatUtil.java:56)
        at com.pattexpattex.servergods2.util.FormatUtil.kvintakordEmbed(FormatUtil.java:88)
        at com.pattexpattex.servergods2.util.FormatUtil.kvintakordEmbed(FormatUtil.java:103)
        at com.pattexpattex.servergods2.util.FormatUtil.getQueueEmbed(FormatUtil.java:429)
        at com.pattexpattex.servergods2.core.Kvintakord.updateLastQueueMessage(Kvintakord.java:804)
        at com.pattexpattex.servergods2.commands.button.music.LoopButton.run(LoopButton.java:41)
        ...
```

**Comment by PattexPattex** [comment]
`/music queue short` will not be added.
